services:
  transcoder-web:
    container_name: transcoder-web
    image: ghcr.io/bob-park/transcoder-web
    build:
      context: ./
      dockerfile: ./Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
